/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pkg1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author shahab
 */
public class HomePage extends javax.swing.JFrame {

    public int amount = 29999;

    /**
     * Creates new form HomePage
     */
    public HomePage() {
        initComponents();
    }

    private boolean ifEmptyFeild() {
        boolean bool = true;
        if (first_name.getText().equals("") || last_name.getText().equals("") || father_name.getText().equals("") || cnic.getText().equals("") || phone.getText().equals("") || email.getText().equals("") || password.getText().equals("") || dof.getText().equals("") || address.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Enter required Information.");
            bool = false;
        } else if (password.getText().equals(c_password.getText())) {
            passwordLabel.setText(" ");
            bool = true;
        } else {
            passwordLabel.setText("*PIN Mismatch ");
            bool = false;
        }
        return bool;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cnic = new javax.swing.JTextField();
        c_password = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        father_name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fatherName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        email = new javax.swing.JTextField();
        dof = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        showPin = new javax.swing.JCheckBox();
        adress = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        register = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1600, 900));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("First Name ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 114, -1));

        first_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                first_nameActionPerformed(evt);
            }
        });
        jPanel1.add(first_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 143, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 86, -1));

        last_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                last_nameActionPerformed(evt);
            }
        });
        jPanel1.add(last_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 129, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Mobile number ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 126, -1));

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });
        jPanel1.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 137, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("CNIC");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 68, -1));

        cnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicActionPerformed(evt);
            }
        });
        jPanel1.add(cnic, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 129, -1));

        c_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(c_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, 129, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Date of Birth");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 22));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Confrim PIN");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, -1));
        jPanel1.add(father_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 129, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Email");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 126, 22));

        fatherName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fatherName.setText("Father Name");
        jPanel1.add(fatherName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 97, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("PIN");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 38, 22));
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 137, -1));
        jPanel1.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 137, -1));

        dof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dofActionPerformed(evt);
            }
        });
        jPanel1.add(dof, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 137, -1));

        passwordLabel.setForeground(new java.awt.Color(255, 0, 0));
        passwordLabel.setText("  ");
        jPanel1.add(passwordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, 84, -1));

        showPin.setText("show PIN");
        showPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPinActionPerformed(evt);
            }
        });
        jPanel1.add(showPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 290, 86, 21));

        adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressActionPerformed(evt);
            }
        });
        jPanel1.add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 459, 27));

        address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        address.setText("Address");
        jPanel1.add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 82, 27));

        register.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        register.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\registration.png")); // NOI18N
        register.setText("Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        jPanel1.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 188, -1));

        back.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        back.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\Back.png")); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 100, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\registration1.png")); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 90, 90));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 690, 530));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\login.png")); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -110, 1620, 1130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new Loginpage().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_backActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        if (ifEmptyFeild() == true) {
            Connection con = null;
            try {
                System.out.println("before class");
                con = ProvideConnection.getConnection(con);
                System.out.println("after class");
                //"insert into atmaccount values(?,?,?,?,?,?,?,?,?,?) "insert into atmaccount values(CNIC,fname,lname,fathername,dob,phone,email,amount,password,address(?,?,?,?,?,?,?,?,?,?))
                String query = "insert into atmaccount values(?,?,?,?,?,?,?,?,?,?)";

                PreparedStatement pps = con.prepareStatement(query);
                pps.setString(1, cnic.getText());
                System.out.println("added");
                pps.setString(2, first_name.getText());
                System.out.println("added");
                pps.setString(3, last_name.getText());
                System.out.println("added");
                pps.setString(4, father_name.getText());
                System.out.println("added");
                pps.setString(5, email.getText());
                System.out.println("added");
                pps.setString(6, phone.getText());
                System.out.println("added");
                pps.setString(7, dof.getText());
                System.out.println("added");
                pps.setString(8, "0");
                System.out.println("added");
                pps.setString(9, password.getText());
                System.out.println("added");
                pps.setString(10, address.getText());
                System.out.println("added");
                System.out.println("before execution");

                pps.executeUpdate();
                System.out.println("after execution");
                this.setVisible(false);
                new Loginpage().setVisible(true);

                con.close();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "System Error! /nTry Later");
            }        // TODO add your handling code here:
        }
    }//GEN-LAST:event_registerActionPerformed

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_registerMouseClicked

    private void showPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPinActionPerformed
        if (showPin.isSelected()) {
            password.setEchoChar((char) 0);
            c_password.setEchoChar((char) 0);
        } else {
            password.setEchoChar('*');
            c_password.setEchoChar('*');
        }
    }//GEN-LAST:event_showPinActionPerformed

    private void dofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dofActionPerformed

    private void c_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_passwordActionPerformed

    private void cnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed

    }//GEN-LAST:event_phoneActionPerformed

    private void last_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_last_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_last_nameActionPerformed

    private void first_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_first_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_first_nameActionPerformed

    private void adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel address;
    private javax.swing.JTextField adress;
    private javax.swing.JButton back;
    private javax.swing.JPasswordField c_password;
    private javax.swing.JTextField cnic;
    private javax.swing.JTextField dof;
    private javax.swing.JTextField email;
    private javax.swing.JLabel fatherName;
    private javax.swing.JTextField father_name;
    private javax.swing.JTextField first_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField last_name;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField phone;
    private javax.swing.JButton register;
    private javax.swing.JCheckBox showPin;
    // End of variables declaration//GEN-END:variables
}
