/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pkg1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Lenovo
 */
public class Money extends javax.swing.JFrame {

    /**
     * Creates new form Money
     */
    public Money() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        one = new javax.swing.JButton();
        twenty = new javax.swing.JButton();
        twentyfive = new javax.swing.JButton();
        five = new javax.swing.JButton();
        ten = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        otheramount = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1600, 900));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 255));
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\Back.png")); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, -1, -1));

        one.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        one.setForeground(new java.awt.Color(51, 102, 255));
        one.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\money.png")); // NOI18N
        one.setText("1000");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel2.add(one, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, -1));

        twenty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        twenty.setForeground(new java.awt.Color(51, 102, 255));
        twenty.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\money.png")); // NOI18N
        twenty.setText("20000");
        twenty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyActionPerformed(evt);
            }
        });
        jPanel2.add(twenty, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 123, -1));

        twentyfive.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        twentyfive.setForeground(new java.awt.Color(51, 102, 255));
        twentyfive.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\money.png")); // NOI18N
        twentyfive.setText("25000");
        twentyfive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twentyfiveActionPerformed(evt);
            }
        });
        jPanel2.add(twentyfive, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 130, -1));

        five.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        five.setForeground(new java.awt.Color(51, 102, 255));
        five.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\money.png")); // NOI18N
        five.setText("5000");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel2.add(five, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 120, -1));

        ten.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ten.setForeground(new java.awt.Color(51, 102, 255));
        ten.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\money.png")); // NOI18N
        ten.setText("10000");
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });
        jPanel2.add(ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 120, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CHOOSE AMOUNT");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 270, 60));

        otheramount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        otheramount.setForeground(new java.awt.Color(51, 102, 255));
        otheramount.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\otherOption.png")); // NOI18N
        otheramount.setText("Other Amount");
        otheramount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otheramountActionPerformed(evt);
            }
        });
        jPanel2.add(otheramount, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 160, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\login.png")); // NOI18N
        jLabel3.setText("Back");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, 740, 510));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 560, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\login.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1600, 900));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void myExecution(int value){
        Connection con = null;
        int input = value;
        int amount = 0;
        int result = 0;
        try {
            con = ProvideConnection.getConnection(con);
            String query = "select amount,fname,lname from atmaccount where CNIC='"+Loginpage.getCNIC()+"'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                amount = Integer.parseInt(rs.getString("amount"));
                String name=rs.getString("fname")+" "+ rs.getString("lname");
                GetData.setName(name);
            }
            if (input < amount) {
                result = amount - input;
                GetData.setMoney(Integer.toString(result));
                query = "update atmaccount set amount=? where CNIC=" + Loginpage.getCNIC();
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, Integer.toString(result));
                try {
                    pst.executeUpdate();
                    pst.close();
                    //System.out.println("Execute2");
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "System Error!");
                    System.exit(0);
                }
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "System Error!");
            System.exit(0);
        }
        int result1=JOptionPane.showConfirmDialog(null,"Do you want recipt?","Swing Tester",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (result1==JOptionPane.YES_OPTION){
                this.setVisible(false);
                new Recipt().setVisible(true);
            }else if (result1==JOptionPane.NO_OPTION){
                this.setVisible(false);
                new Loginpage().setVisible(true);
            }
    }
    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        GetData.setWithdraw(Integer.toString(1000));
        myExecution(1000);
    }//GEN-LAST:event_oneActionPerformed

    private void twentyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyActionPerformed
        GetData.setWithdraw(Integer.toString(20000));
        myExecution(20000);
    }//GEN-LAST:event_twentyActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        GetData.setWithdraw(Integer.toString(5000));
        myExecution(5000);
    }//GEN-LAST:event_fiveActionPerformed

    private void twentyfiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twentyfiveActionPerformed
        GetData.setWithdraw(Integer.toString(25000));
        myExecution(25000);
    }//GEN-LAST:event_twentyfiveActionPerformed

    private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed
        GetData.setWithdraw(Integer.toString(10000));
        myExecution(10000);
    }//GEN-LAST:event_tenActionPerformed

    private void otheramountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otheramountActionPerformed
        this.setVisible(false);
        new withdraw().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_otheramountActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new FirstPage().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Money.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Money().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton five;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton one;
    private javax.swing.JButton otheramount;
    private javax.swing.JButton ten;
    private javax.swing.JButton twenty;
    private javax.swing.JButton twentyfive;
    // End of variables declaration//GEN-END:variables
}
