/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pkg1;

import com.mysql.cj.xdevapi.Result;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shahab
 */
public class withdraw extends javax.swing.JFrame {

    /**
     * Creates new form withdraw
     */
    public withdraw() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        enter = new javax.swing.JButton();
        money = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setPreferredSize(new java.awt.Dimension(1600, 900));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 155, 23, 62));

        Cancel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(51, 102, 255));
        Cancel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\cancellation.png")); // NOI18N
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        enter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enter.setForeground(new java.awt.Color(51, 102, 255));
        enter.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\confirmation.png")); // NOI18N
        enter.setText("Enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });
        jPanel1.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, -1, -1));

        money.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        money.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyActionPerformed(evt);
            }
        });
        jPanel1.add(money, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 230, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\money.png")); // NOI18N
        jLabel3.setText("Enter Amount");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 209, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\login.png")); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 270));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 600, 260));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Lenovo\\Desktop\\ATMProject\\src\\main\\java\\Pkg1\\Images\\login.png")); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1690, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyActionPerformed
    ResultSet rs;
    String query = "";
    private static int paisey = 0;
    private static int inputPaisey;
    Statement st;
    static String name;
    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        Connection con = null;

        inputPaisey = Integer.parseInt(money.getText());
        if (inputPaisey % 500 != 0) {
            JOptionPane.showMessageDialog(null, "Incorect Value");
        } else {
            try {
                con = ProvideConnection.getConnection(con);

                query = "select amount,fname,lname from atmaccount where CNIC='"+Loginpage.getCNIC()+"'";

                //pst.setString(1, Loginpage.getCNIC());
                System.out.println("CNIC : " + Loginpage.getCNIC());
                st=con.createStatement();
                rs = st.executeQuery(query);
                //System.out.println("execute");
                while (rs.next()) {
                    paisey = Integer.parseInt(rs.getString("amount"));
                    name=rs.getString("fname")+" "+ rs.getString("lname");
                    GetData.setName(name);
                    //System.out.println(paisey);

                }
                if (paisey > inputPaisey) {
                    con=ProvideConnection.getConnection(con);
                    query = "update atmaccount set amount=? where CNIC='"+Loginpage.getCNIC()+"'";
                    PreparedStatement pst=con.prepareStatement(query);
                    pst.setString(1,Integer.toString(paisey-inputPaisey));
                    try {
                        pst.executeUpdate();
                        pst.close();
                        //System.out.println("Execute2");
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null, "System Error!");
                        System.exit(0);
                    }
                }
                //rs.refreshRow();
                //rs.close();
                //con.close();
                
               // new Yes_NO().setVisible(true);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                System.exit(0);
            }
            int result=JOptionPane.showConfirmDialog(null,"Do you want recipt?","Swing Tester",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (result==JOptionPane.YES_OPTION){
                this.setVisible(false);
                GetData.setWithdraw(money.getText());
                new Recipt().setVisible(true);
            }else if (result==JOptionPane.NO_OPTION){
                this.setVisible(false);
                new Loginpage().setVisible(true);
            }
            

        }

    }//GEN-LAST:event_enterActionPerformed
    
    public static String getwithDrawAmount(){
        return Integer.toString(inputPaisey);
    }
     public static String getRemainingAmount(){
        int result=paisey-inputPaisey;
        return Integer.toString(result);
    }
     public static String getBalance(){
         System.out.println(""+paisey);
         return Integer.toString(paisey);
         
     }
    
    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FirstPage().setVisible(true);
    }//GEN-LAST:event_CancelActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton enter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField money;
    // End of variables declaration//GEN-END:variables
}
